Repository Dosirak-semiProject/Dosirak, pull requests merged in 2024-04, with the labels that each got.

#9 admin/common
  Dosirak/src/main/java/com/ohgiraffers/dosirak/config/Application.java
Labels: Priority: High, Type: Feature

#10 #4 설문 페이지의 html/css 갱신
  Dosirak/src/main/resources/static/user/css/survey.css
  Dosirak/src/main/resources/templates/user/survey/html/surveyAgree.html
  Dosirak/src/main/resources/templates/user/survey/html/surveyInfo.html
  Dosirak/src/main/resources/templates/user/survey/html/surveyMain.html
  Dosirak/src/main/resources/templates/user/survey/html/surveyResult.html
  Dosirak/src/main/resources/templates/user/survey/sample.html
Labels: Priority: High, Type: Feature

#15 Feature/4 survey fix
  Dosirak/src/main/resources/static/user/css/survey.css
  Dosirak/src/main/resources/static/user/js/surveyProgressIndex.js
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxLIst.html
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxView.html
  Dosirak/src/main/resources/templates/admin/survey/sample.html
  Dosirak/src/main/resources/templates/admin/survey/surveyList.html
  Dosirak/src/main/resources/templates/admin/survey/surveyStatus.html
  Dosirak/src/main/resources/templates/user/suitBox/html/productView_suitBox.html
  Dosirak/src/main/resources/templates/user/survey/html/surveyAgree.html
  Dosirak/src/main/resources/templates/user/survey/html/surveyMain.html
  Dosirak/src/main/resources/templates/user/survey/js/surveyProgressIndex.js
Labels: Priority: Medium, Type: Improvement

#21 #16 survey 데이터베이스 연동
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/survey/Sample.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/survey/controller/SurveyAdminController.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/survey/model/dao/SurveyAdminMapping.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/survey/model/dto/SurveyResultDTO.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/survey/model/service/SurveyAdminService.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/user/suitBox/controller/SuitBoxController.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/user/suitBox/model/dao/SuitBoxMapper.java
  Dosirak/src/main/resources/mappers/admin/SurveyMapper.xml
  Dosirak/src/main/resources/templates/admin/survey/surveyList.html
  Dosirak/src/main/resources/templates/user/suitBox/productView_suitBox.html
Labels: Priority: Medium, Type: Feature

#38 #22 관리자 맞춤 도시락 메뉴 탭 기본적인 기능 구현
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/controller/AdminSuitBoxController.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/model/dao/AdminSuitBoxDAO.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/model/dto/SuitBoxMenuDTO.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/model/service/AdminSuitBoxService.java
  Dosirak/src/main/resources/mappers/admin/SuitBoxMapper.xml
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxLIst.html
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxMenuSet.html
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxMenuView.html
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxView.html
Labels: Priority: Medium, Type: Feature

#43 #22 suit-box 관리자 페이지 기본 기능 구현 완료
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/controller/AdminSuitBoxController.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/model/dao/AdminSuitBoxDAO.java
  Dosirak/src/main/java/com/ohgiraffers/dosirak/admin/suitBox/model/service/AdminSuitBoxService.java
  Dosirak/src/main/resources/mappers/admin/SuitBoxMapper.xml
  Dosirak/src/main/resources/templates/admin/suitBox/suitBoxMenuView.html
Labels: Priority: Medium, Type: Feature
